In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
a

array([1, 2, 3, 4, 5])

In [8]:
b = np.array([[1,2,3,4],[2,3,4,5],[7,6,4,3],[8,9,2,3]])
type(b)

numpy.ndarray

In [9]:
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [7, 6, 4, 3],
       [8, 9, 2, 3]])

In [10]:
a1 = np.zeros(10)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
a2 = np.ones(10)
a2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
# Mathematical Operations
add = np.sum(a)
min = np.min(a)
max = np.max(a)
mean = np.mean(a)
med = np.median(a)
std = np.std(a)
q1 = np.quantile(a,0.0) 
q2 = np.quantile(a,0.25) 
q3 = np.quantile(a,0.50) 
q4 = np.quantile(a,0.75) 
q5 = np.quantile(a,1.0)
print(add)
print(min)
print(max)
print(mean)
print(med)
print(std)
print(q1)
print(q2)
print(q3)
print(q4)
print(q5)

15
1
5
3.0
3.0
1.4142135623730951
1.0
2.0
3.0
4.0
5.0


In [16]:
a1 = np.arange(1,11,2)
a1

array([1, 3, 5, 7, 9])

In [20]:
a2 = np.linspace(1,10)
a2

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [22]:
print(np.ndim(a2))
print(np.shape(a2))

1
(50,)


In [28]:
a2 = a2.reshape(25,2)

In [30]:
print(np.ndim(a2))
print(np.shape(a2))

2
(25, 2)


In [31]:
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [7, 6, 4, 3],
       [8, 9, 2, 3]])

In [32]:
b.T

array([[1, 2, 7, 8],
       [2, 3, 6, 9],
       [3, 4, 4, 2],
       [4, 5, 3, 3]])

In [33]:
np.transpose(b)

array([[1, 2, 7, 8],
       [2, 3, 6, 9],
       [3, 4, 4, 2],
       [4, 5, 3, 3]])

In [35]:
b2 = b.flatten()
b2

array([1, 2, 3, 4, 2, 3, 4, 5, 7, 6, 4, 3, 8, 9, 2, 3])

In [36]:
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [7, 6, 4, 3],
       [8, 9, 2, 3]])

In [37]:
a[1:]

array([2, 3, 4, 5])

In [38]:
a[::-1]

array([5, 4, 3, 2, 1])

In [39]:
b[1:3,1:3]

array([[3, 4],
       [6, 4]])

In [40]:
b[0::2,1:3]

array([[2, 3],
       [6, 4]])

In [41]:
b[1:3,0:3]

array([[2, 3, 4],
       [7, 6, 4]])